{{- if .Values.conversionManager.enabled -}}
{{- if .Values.conversionManager.ingress.enabled -}}
{{- $fullName := include "app.conversion-manager.fullname" . -}}
{{- $httpPort := .Values.conversionManager.service.http.port -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.conversionManager.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.conversionManager.ingress.ingressClassName }}
  ingressClassName: {{ .Values.conversionManager.ingress.ingressClassName }}
{{- end }}
{{- if .Values.conversionManager.ingress.tls }}
  tls:
  {{- range .Values.conversionManager.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    {{- range .Values.conversionManager.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
            {{- if .backend }}
              service:
                name: {{ .backend.service.name }}
                port:
                  {{- if .backend.service.port.number }}
                  number: {{ .backend.service.port.number }}
                  {{- else if .backend.service.port.name }}
                  name: {{ .backend.service.port.name }}
                  {{- end }}
            {{- else }}
              service:
                name: {{ $fullName }}-http
                port:
                  number: {{ $httpPort }}
            {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
