---
apiVersion: v1
kind: Secret
metadata:
  name: copia-preflight
  labels: 
    app: copia
    app.kubernetes.io/name: copia
    app.kubernetes.io/instance: copia
    troubleshoot.sh/kind: preflight
stringData:
  preflight.yaml: |- {{- include "troubleshoot.preflights" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: copia-support-bundle
  labels: 
    app: copia
    app.kubernetes.io/name: copia
    app.kubernetes.io/instance: copia
    troubleshoot.sh/kind: support-bundle
stringData:
  support-bundle-spec: |- {{- include "troubleshoot.supportBundle" . | nindent 4 }}
