{{- if and .Values.conversion_manager.secret (eq .Values.conversion_manager.enabled true)}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.conversion-manager.fullname" . }}-secret
  labels:
    {{- include "app.conversion-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.conversion_manager.secret }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
