{{- if .Values.conversion_manager.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-cm-secret
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.conversion_manager.secret }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
