{{- if .Values.copia.config.server }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-configmap
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.copia.config.server }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
