{{- if and .Values.conversion_manager_service.secret (eq .Values.conversion_manager_service.enabled true)}}
{{- $secrets := deepCopy .Values.conversion_manager_service.secret -}}
{{- if and .Values.chartGeneratedSecrets .Values.chartGeneratedSecrets.enabled }}
  {{- $_ := unset $secrets "MANAGEMENT_TOKEN" -}}
  {{- $_ := unset $secrets "WORKER_TOKEN" -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.conversion-manager.fullname" . }}-secret
  labels:
    {{- include "app.conversion-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := $secrets }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
