{{- if hasKey .Values.copia "config" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-ini
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  app.ini: |
    {{- /* autogenerate app.ini */ -}}
    {{- $autoGen := and .Values.chartGeneratedSecrets .Values.chartGeneratedSecrets.enabled -}}
    {{- $cfg := deepCopy .Values.copia.config -}}
    {{- if $autoGen -}}
      {{- $autoGenKeys := list
            (list "security" "INTERNAL_TOKEN")
            (list "security" "SECRET_KEY")
            (list "oauth2"   "JWT_SECRET")
            (list "server"   "LFS_JWT_SECRET")
            (list "copia"    "USER_SECRETS_PUBLIC_KEY")
            (list "copia"    "USER_SECRETS_PRIVATE_KEY") -}}
      {{- range $pair := $autoGenKeys -}}
        {{- $section := index $pair 0 -}}
        {{- $key := index $pair 1 -}}
        {{- if not (hasKey $cfg $section) -}}
          {{- $_ := set $cfg $section dict -}}
        {{- end -}}
        {{- $sectionMap := index $cfg $section -}}
        {{- if not (index $sectionMap $key) -}}
          {{- $_ := set $sectionMap $key (printf "###%s###" $key) -}}
        {{- end -}}
      {{- end -}}
    {{- end -}}
    {{- range $key, $value := $cfg }}
    {{- if kindIs "map" $value }}
    {{- if gt (len $value) 0 }}

    [{{ $key }}]
    {{- range $n_key, $n_value := $value }}
    {{ $n_key | upper }} = {{ $n_value }}
    {{- end }}
    {{- end }}
    {{- else }}
    {{ $key | upper }} = {{ $value }}
    {{- end }}
    {{- end }}
{{- end }}
