---
{{- if eq .Values.ghcrCheck true }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "copia-ghcr-check"
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "copia-ghcr-check"
      labels:
        {{- include "app.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: pre-install-job-ghcr
        image: "{{ include "app.image" . }}"
        imagePullPolicy: Always
        command: ["/bin/sleep", "{{ .Values.sleepTime | default "5" }}"]
{{- end }}
