apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  revisionHistoryLimit: 2
  strategy:
    {{- if and .Values.deployment.strategy (eq .Values.deployment.strategy "Recreate") }}
    type: Recreate
    {{- else }}
    type: RollingUpdate
    rollingUpdate:
      {{- with .Values.deployment.rollingUpdate }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        {{- with .Values.conversionManager.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "app.labels" . | nindent 8 }}
        {{- if .Values.deployment.labels }}
        {{- toYaml .Values.deployment.labels | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.serviceAccountName }}
      serviceAccountName: "{{ .Values.deployment.serviceAccountName }}"
      {{- end }}
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ include "app.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - gitea
          env:
            # SSH Port values have to be set here as well for openssh configuration
            {{- if (hasKey .Values.conversionManager "config") }}
            - name: SSH_LISTEN_PORT
              value: {{ .Values.conversionManager.config.server.SSH_LISTEN_PORT | default "22" | quote }}
            - name: SSH_PORT
              value: {{ .Values.conversionManager.config.server.SSH_PORT | default "22" | quote }}
            {{- else }}
            - name: SSH_LISTEN_PORT
              value: "22"
            - name: SSH_PORT
              value: "22"
            {{- end }}
            - name: GITEA_APP_INI
              value: /data/gitea/conf/app.ini
            - name: GITEA_CUSTOM
              value: /data/gitea
            - name: GITEA_WORK_DIR
              value: /data
            - name: GITEA_TEMP
              value: /tmp/gitea
            - name: TMPDIR
              value: /tmp/gitea
            {{- if .Values.signing.enabled }}
            - name: GNUPGHOME
              value: {{ .Values.signing.gpgHome }}
            {{- end }}
            {{- if .Values.deployment.env }}
            {{- toYaml .Values.deployment.env | nindent 12 }}
            {{- end }}
          ports:
            {{- if (hasKey .Values.conversionManager "config") }}
            - name: ssh
              containerPort: {{ .Values.conversionManager.config.server.SSH_LISTEN_PORT | default "22" }}
            - name: http
              containerPort: {{ .Values.conversionManager.config.server.HTTP_PORT | default "4001" }}
              {{- if .Values.conversionManager.config.server.ENABLE_PPROF }}
            - name: profiler
              containerPort: 6060
              {{- end }}
            {{- else }}
            - name: ssh
              containerPort: 22
            - name: http
              containerPort: 4001
            {{- end }}
          lifecycle:
            preStop:
              exec:
                command: [
                  "sh", "-c",
                  "sleep 10 && /usr/local/bin/gitea manager shutdown",
                ]
          {{- if .Values.conversionManager.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.conversionManager.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.conversionManager.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.conversionManager.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.conversionManager.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.conversionManager.livenessProbe.failureThreshold }}
          {{- else if .Values.conversionManager.customLivenessProbe }}
          livenessProbe:
            {{- toYaml .Values.conversionManager.customLivenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.conversionManager.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.conversionManager.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.conversionManager.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.conversionManager.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.conversionManager.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.conversionManager.readinessProbe.failureThreshold }}
          {{- else if .Values.conversionManager.customReadinessProbe }}
          readinessProbe:
            {{- toYaml .Values.conversionManager.customReadinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.conversionManager.startupProbe.enabled }}
          startupProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.conversionManager.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.conversionManager.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.conversionManager.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.conversionManager.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.conversionManager.startupProbe.failureThreshold }}
          {{- else if .Values.conversionManager.customStartupProbe }}
          startupProbe:
            {{- toYaml .Values.conversionManager.customStartupProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name     : temp
              mountPath: /tmp/gitea
            - name     : data
              mountPath: /data
            {{- if (hasKey .Values.conversionManager "config") }}
            - name     : config
              mountPath: /data/gitea/conf/app.ini
              subPath  : app.ini
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        {{- if (hasKey .Values.conversionManager "config") }}
        - name: config
          secret:
            secretName: {{ include "app.fullname" . }}-ini
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
        - name: temp
          emptyDir: {}
  {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
  {{- with .Values.persistence.existingClaim }}
            claimName: {{ tpl . $ }}
  {{- end }}
  {{- else if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "app.fullname" . }}-data
  {{- end }}
