replicaCount: 1
clusterDomain: cluster.local
image:
  repository: ghcr.io/copia-automation/copia-web-app-release
  pullPolicy: Always
imagePullSecrets:
  - name: ghcr-login-secret
service:
  http:
    type: NodePort
    port: 3000
    targetPort: 4001
    # clusterIP: None
    #loadBalancerIP:
    #nodePort:
    #externalTrafficPolicy:
    #externalIPs:
    loadBalancerSourceRanges: []
    annotations:
ingress:
  enabled: false
  # ingressClassName: nginx
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: git.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - git.example.com
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
## Use an alternate scheduler, e.g. "stork".
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
# schedulerName:
nodeSelector: {}
tolerations: []
affinity: {}
deployment:
  env:
    # - name: ACD_CONVERSION_URL
    #   value: https://rockwell-tools.copia.io/convertOctetStream
    # - name: ROCKWELL_V35_CONVERSION_URL
    #   value: https://rockwell-v35.copia.io/convertOctetStream
    # - name: ROCKWELL_V35_IMPORT_CONVERSION_URL
    #   value: https://rockwell-v35.copia.io/convertL5xToAcd
    # - name: ZAP14_CONVERSION_URL
    #   value: http://zap2zipv14.copia.io:9694
    # - name: ZAP15_0_CONVERSION_URL
    #   value: http://zap2zipv15-0.copia.io:9695
    # - name: ZAP15_CONVERSION_URL
    #   value: http://zap2zipv15.copia.io:9695
    # - name: ZAP16_CONVERSION_URL
    #   value: http://zap2zip.copia.io:9696
    # - name: ZAP17_CONVERSION_URL
    #   value: http://zap2zipv17.copia.io:9697
    # - name: ACD_IMPORT_CONVERSION_URL
    #   value: https://rockwell-tools.copia.io/convertL5xToAcd
    # - name: ZAP14_IMPORT_CONVERSION_URL
    #   value: http://zap2zipv14.copia.io:9694/import
    # - name: ZAP15_0_IMPORT_CONVERSION_URL
    #   value: http://zap2zipv15-0.copia.io:9695/import
    # - name: ZAP15_IMPORT_CONVERSION_URL
    #   value: http://zap2zipv15.copia.io:9695/import
    # - name: ZAP16_IMPORT_CONVERSION_URL
    #   value: http://zap2zip.copia.io:9696/import
    # - name: ZAP17_IMPORT_CONVERSION_URL
    #   value: http://zap2zipv17.copia.io:9697/import
    # - name: CODESYS_CONVERSION_URL
    #   value: http://codesys.copia.io:8888/export
    # - name: CODESYS_IMPORT_CONVERSION_URL
    #   value: http://codesys.copia.io:8888/import
    # - name: CONTROL_EXPERT_CONVERSION_URL
    #   value: http://control-expert.copia.io:9696/export
  terminationGracePeriodSeconds: 60
  labels: {}
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
persistence:
  enabled: true
  existingClaim:
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  labels: {}
  annotations: {}
  # storageClass:
# additional volumes to add to the deployment.
extraVolumes:
extraVolumeMounts:
# bash shell script copied verbatim to the start of the init-container.
initPreScript: ""
# Configure commit/action signing prerequisites
signing:
  enabled: false
  gpgHome: /data/git/.gnupg
copia:
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: false
  customStartupProbe:
    httpGet:
      path: /
      port: 4001
    initialDelaySeconds: 10
    periodSeconds      : 5
    timeoutSeconds     : 2
    failureThreshold   : 10
  customLivenessProbe:
    httpGet:
      path: /
      port: 4001
    periodSeconds   : 10
    timeoutSeconds  : 2
    failureThreshold: 2
  # config:
  #   APP_NAME: "Copia"
  #   RUN_MODE: production
  #   oauth2:
  #     JWT_SECRET: <REQUIRED>
  #   security:
  #     INTERNAL_TOKEN: <REQUIRED>
  #   server:
  #     LFS_JWT_SECRET: <REQUIRED>
  #   copia:
  #     LICENSE_KEY: <REQUIRED>
