replicaCount: 1
clusterDomain: cluster.local
#Use this value "*copia_port" to reference the value of the copia_server_http_port when setting HTTP_PORT on the copia config.
copia_server_http_port: &copia_port 4001
image:
  repository: ghcr.io/copia-automation/copia-web-app-selfhosted-releases
  pullPolicy: Always
imagePullSecrets:
  - name: ghcr-login-secret
service:
  #clusterIP: None
  #loadBalancerIP:
  #externalTrafficPolicy:
  #externalIPs: []
  loadBalancerSourceRanges: []
  annotations: {}
  http:
    type: NodePort
    port: 3000
    targetPort: *copia_port
    #nodePort:
    annotations: {}
ingress:
  enabled: false
  # ingressClassName: nginx
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: git.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - git.example.com
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
## Use an alternate scheduler, e.g. "stork".
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
# schedulerName:
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
deployment:
  configmap:
    SSH_LISTEN_PORT: 22
    GITEA_APP_INI: /data/gitea/conf/app.ini
    GITEA_CUSTOM: /data/gitea
    GITEA_WORK_DIR: /data
    GITEA_TEMP: /tmp/gitea
    TMPDIR: /tmp/gitea
    ENABLE_PPROF: false
    PPROF_PORT: 6060
    # ACD_CONVERSION_URL: https://rockwell-tools.copia.io/convertOctetStream
    # ROCKWELL_V35_CONVERSION_URL: https://rockwell-v35.copia.io/convertOctetStream
    # ROCKWELL_V35_IMPORT_CONVERSION_URL: https://rockwell-v35.copia.io/convertL5xToAcd
    # ZAP14_CONVERSION_URL: http://zap2zipv14.copia.io:9694
    # ZAP15_0_CONVERSION_URL: http://zap2zipv15-0.copia.io:9695
    # ZAP15_CONVERSION_URL: http://zap2zipv15.copia.io:9695
    # ZAP16_CONVERSION_URL: http://zap2zip.copia.io:9696
    # ZAP17_CONVERSION_URL: http://zap2zipv17.copia.io:9697
    # ACD_IMPORT_CONVERSION_URL: https://rockwell-tools.copia.io/convertL5xToAcd
    # ZAP14_IMPORT_CONVERSION_URL: http://zap2zipv14.copia.io:9694/import
    # ZAP15_0_IMPORT_CONVERSION_URL: http://zap2zipv15-0.copia.io:9695/import
    # ZAP15_IMPORT_CONVERSION_URL: http://zap2zipv15.copia.io:9695/import
    # ZAP16_IMPORT_CONVERSION_URL: http://zap2zip.copia.io:9696/import
    # ZAP17_IMPORT_CONVERSION_URL: http://zap2zipv17.copia.io:9697/import
    # CODESYS_CONVERSION_URL: http://codesys.copia.io:8888/export
    # CODESYS_IMPORT_CONVERSION_URL: http://codesys.copia.io:8888/import
    # CONTROL_EXPERT_CONVERSION_URL: http://control-expert.copia.io:9696/export
  env: []
  terminationGracePeriodSeconds: 60
  labels: {}
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
persistence:
  enabled: true
  existingClaim: ""
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  labels: {}
  annotations: {}
  #storageClassName:
# additional volumes to add to the deployment.
extraVolumes: []
extraVolumeMounts: []
# bash shell script copied verbatim to the start of the init-container.
initPreScript: ""
# Configure commit/action signing prerequisites
signing:
  enabled: false
  gpgHome: /data/git/.gnupg
copia:
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: false
  customStartupProbe:
    httpGet:
      path: /
      port: *copia_port
    initialDelaySeconds: 10
    periodSeconds      : 5
    timeoutSeconds     : 2
    failureThreshold   : 10
  customLivenessProbe:
    httpGet:
      path: /
      port: *copia_port
    periodSeconds   : 10
    timeoutSeconds  : 2
    failureThreshold: 2
  # config:
  #   server:
  #     SSH_PORT: 22
  #     HTTP_PORT: *copia_port
  #     LFS_JWT_SECRET: <REQUIRED>
  #   APP_NAME: "Copia"
  #   RUN_MODE: production
  #   oauth2:
  #     JWT_SECRET: <REQUIRED>
  #   security:
  #     INTERNAL_TOKEN: <REQUIRED>
  #   copia:
  #     LICENSE_KEY: <REQUIRED>
conversion_manager:
  enabled: true
  deployment:
    port: 8080
    image:
      repository: ghcr.io/copia-automation/conversion-manager
      imagePullPolicy: Always
      tag: latest
    # serviceAccountName: ""
    # terminationGracePeriodSeconds: 60
    replicaCount: 1
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    podAnnotations: {}
    labels: {}
    imagePullSecrets:
      - name: ghcr-login-secret
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  configmap: {}
