name: Publish Beta Helm Chart to Development Container Registry

on:
  pull_request:

permissions: write-all

jobs:
  publish:
    uses: ./.github/workflows/publish-helm-chart.yaml
    with:
      version: 0.0.0-beta.pr${{ github.event.pull_request.number }}
