name: Release Charts

on:
  # TODO: uncomment release trigger and remove push, workflow_dispatch triggers
  # release:
  #   types: [published]
  push:
    branches:
      - '04-07-automate_helm_chart_releases'
  workflow_dispatch:

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "placeholder"
