name: Release Charts

on:
  pull_request:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
  
      - name: Package Helm chart
        run: helm package ./charts/copia
  
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
  
      - name: Push Helm chart to GitHub Container Registry
        run: helm push copia-*.tgz oci://ghcr.io/copia-automation/helm-charts
