name: Security Scan

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner on postgres image
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          image-ref: 'docker.io/postgres:latest'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
