name: Security Scan

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner on postgres image
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # 0.30.0
        with:
          image-ref: 'docker.io/postgres:latest'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
