name: Security Scan

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner on postgres image
        uses: aquasecurity/trivy-action@c5967f85626795f647d4bf6eb67227f9b79e02f5 # 0.28.0
        with:
          image-ref: 'docker.io/postgres:latest'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
