name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:

permissions: write-all

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner on postgres image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'docker.io/postgres:latest'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
